plugins { id "com.android.application" }

android {
    namespace "com.ls400.toolbox"
    compileSdk 35

    defaultConfig {
        applicationId "com.ls400.toolbox"
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName "2.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
